# failcore/cli/renderers/html/layout.py
"""
HTML document layout and structure
"""

from ...views.trace_report import TraceReportView
from .styles import get_css, get_javascript


def render_html_document(
    view: TraceReportView,
    created_at_display: str,
    content_html: str,
) -> str:
    """Render complete HTML document structure"""
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FailCore Execution Report - {view.meta.run_id}</title>
    <style>
{get_css()}
    </style>
</head>
<body>
    <div class="container">
        {_render_header(view, created_at_display)}
        {content_html}
        {_render_footer(view)}
    </div>
    
    <script>
{get_javascript()}
    </script>
</body>
</html>"""


def _render_header(view: TraceReportView, created_at_display: str) -> str:
    """Render document header"""
    return f"""
        <div class="header">
            <h1>FailCore Execution Report</h1>
            <div class="header-info">
                <div class="header-info-item">
                    <span class="header-info-label">Run ID</span>
                    <span class="header-info-value">{view.meta.run_id}</span>
                </div>
                <div class="header-info-item">
                    <span class="header-info-label">Created</span>
                    <span class="header-info-value">{created_at_display}</span>
                </div>
                <div class="header-info-item">
                    <span class="header-info-label">Sandbox</span>
                    <span class="header-info-value">{view.meta.workspace or '.failcore/sandbox'}</span>
                </div>
                <div class="header-info-item">
                    <span class="header-info-label">Trace</span>
                    <span class="header-info-value">{view.meta.trace_path or 'N/A'}</span>
                </div>
            </div>
        </div>
    """


def _render_footer(view: TraceReportView) -> str:
    """Render document footer"""
    return f"""
        <div class="footer">
            <div class="footer-item">
                <span class="footer-label">Generated by</span>
                <span class="footer-value">FailCore (Trace Schema: v0.1.2)</span>
            </div>
            <div class="footer-item">
                <span class="footer-label">Workspace</span>
                <span class="footer-value">{view.meta.workspace or 'N/A'}</span>
            </div>
        </div>
    """

